### PR TITLE
PR

### PR DESCRIPTION
**Pull request by PetrK39**
# Added auto dark mode features, fixed sexySidebar dark mode handling 650bd02c20eea74f6473fdc6c21b4570a0e0697f
Added auto dark mode using time or system theme preferences
Added config for auto dark mode features
Fixed sexySidebar always in dark mode

# Change sexySidebar behavior 1d825078727687309de3ee1c975724c7a699d839
Now it does not require scrolling to the top of the page

# Apply Gallery Tweaks to More Like This Area 6603a96cfd69e3f1754ebcfbe4d3121fbc14c3de
One of Feature Brainstorm

# Post page improvements f29d6869e2046d974d097102fb6fe1cb64f2c38a
Post can be centered (on by default)
Post now bit bigger
'Click here to expand image' fits post horizontally if config.post.fitVertically was on

### CODE REVIEW

**Comment by PetrK39** [comment]
<sub>sorry for mess in the history<sub>

**Comment by Enchoseon** [comment]
These changes are fantastic! Dark mode stuff can probably be moved to its own section in the config now lol.

**Comment by PetrK39** [comment]
Before I start working on an advanced blacklist (like on danbooru but with multiple sets) I want to refactor
After that, I can start making significant changes. I use gelbooru a lot and have a lot of ideas

**Comment by Enchoseon** [comment]
Sounds good to me. I'm open to refactoring the blacklist and any other major ideas you have. (The only thing I would be against is increasing the scope to include support for other boorus because I want to keep this relatively light and maintainable.)

**Comment by PetrK39** [comment]
I agree. Attempts to add support for booru other than gelbooru 0.2.5 will bloat the script to terrifying volumes

**Pull request merged**
